package harness

import (
	"bytes"
	"fmt"
)

// GenerateTSExtension generates the TypeScript wrapper for pi or opencode.
func GenerateTSExtension(agent string, cmds []HookCommand) ([]byte, bool, error) {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by dotf harness bind; DO NOT EDIT.\n")
	buf.WriteString("import { execSync } from 'child_process';\n\n")

	switch agent {
	case "pi":
		buf.WriteString("export default function(ctx: any) {\n")
		for _, c := range cmds {
			fmt.Fprintf(&buf, "    ctx.on(%q, (ev: any) => {\n", c.Event)
			if c.Event == "tool_call" {
				buf.WriteString("        const payload = JSON.stringify({ session: ctx.conversationId || 'pi', tool: ev.toolName || ev.tool });\n")
				buf.WriteString("        try {\n")
				fmt.Fprintf(&buf, "            execSync(%q, { input: payload, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });\n", c.Command)
				buf.WriteString("        } catch (err: any) {\n")
				buf.WriteString("            ev.block = true;\n")
				buf.WriteString("            ev.reason = err.stderr || err.message || 'Blocked by harness gate';\n")
				buf.WriteString("        }\n")
			} else {
				buf.WriteString("        try {\n")
				fmt.Fprintf(&buf, "            execSync(%q, { stdio: 'ignore' });\n", c.Command)
				buf.WriteString("        } catch (err) {}\n")
			}
			buf.WriteString("    });\n")
		}
		buf.WriteString("}\n")
	case "opencode":
		buf.WriteString("export default function(ctx: any) {\n")
		for _, c := range cmds {
			fmt.Fprintf(&buf, "    ctx.on(%q, (ev: any) => {\n", c.Event)
			if c.Event == "tool_call" {
				buf.WriteString("        const payload = JSON.stringify({ session: ctx.conversationId || 'opencode', tool: ev.toolName || ev.tool });\n")
				buf.WriteString("        try {\n")
				fmt.Fprintf(&buf, "            execSync(%q, { input: payload, encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] });\n", c.Command)
				buf.WriteString("        } catch (err: any) {\n")
				buf.WriteString("            if (ev.output) ev.output.status = 'deny';\n")
				buf.WriteString("            ev.reason = err.stderr || err.message || 'Blocked by harness gate';\n")
				buf.WriteString("        }\n")
			} else {
				buf.WriteString("        try {\n")
				fmt.Fprintf(&buf, "            execSync(%q, { stdio: 'ignore' });\n", c.Command)
				buf.WriteString("        } catch (err) {}\n")
			}
			buf.WriteString("    });\n")
		}
		buf.WriteString("}\n")
	default:
		return nil, false, fmt.Errorf("unsupported agent for ts-extension: %s", agent)
	}

	return buf.Bytes(), true, nil
}
