#!/usr/bin/env bats
# Real-dependency sibling of tests/compile-harness.bats (BUG-055 pairing rule).
#
# compile-harness.bats stubs `dotf` so the agent render can resolve a model tier
# without a Go toolchain. A stub proves what we ASKED the resolver to do; only
# the real binary proves it answers. The two claims that can only diverge here:
#
#   1. the capability probe. The render greps `dotf harness --help` for the
#      subcommand name to tell "too old" from "refused" (#1158). A stub prints
#      whatever we told it to; the real help is generated by cobra from the
#      command tree, and a rename would move it.
#   2. the stdout contract. The model id is captured through $(...), so a value
#      on stderr reads as an empty string at the call site.
#
# `dotf` is OUR binary, built from this tree, so unlike the `gh`/`hive` suites in
# the exemption table a real test costs nothing but a build and mutates nothing.
# The CI `test` job already sets up Go (actions/setup-go, ci.yml), so this runs
# there rather than skipping.

setup() {
    REPO="$BATS_TEST_DIRNAME/.."
    SCRIPT="$REPO/scripts/compile-harness.sh"
    # One build per file, reused across tests in it.
    BIN_DIR="${BATS_FILE_TMPDIR:-/tmp/bats_ch_real_$$}/bin"
    DOTF="$BIN_DIR/dotf"
    if [ ! -x "$DOTF" ]; then
        command -v go >/dev/null 2>&1 || skip "go toolchain not available"
        mkdir -p "$BIN_DIR"
        ( cd "$REPO/cli" && go build -o "$DOTF" ./cmd/dotf ) || skip "dotf failed to build"
    fi
}

@test "real dotf: harness --help lists resolve-tier, which is what the render probes for" {
    run "$DOTF" harness --help
    [ "$status" -eq 0 ]
    # The exact shape scripts/compile-harness.sh greps for in
    # dotf_knows_resolve_tier. If cobra ever stops listing it this way, the probe
    # answers "too old" forever and every agent silently loses its model line.
    printf '%s\n' "$output" | grep -qE '^[[:space:]]*resolve-tier[[:space:]]'
}

@test "real dotf: resolve-tier writes the model id to stdout, not stderr" {
    # Captured the way the render captures it. A value on stderr would make this
    # an empty string, which is the BUG-070 failure the Go side also pins.
    run bash -c "'$DOTF' harness resolve-tier top --harness claude --repo-root '$REPO' 2>/dev/null"
    [ "$status" -eq 0 ]
    [ "$output" = "opus" ]
}

@test "real dotf: an unresolvable tier exits non-zero and writes nothing to stdout" {
    run bash -c "'$DOTF' harness resolve-tier top --harness copilot --repo-root '$REPO' 2>/dev/null"
    [ "$status" -ne 0 ]
    [ -z "$output" ]
}

@test "real dotf: the shipped model-map answers every tier the shipped agent records declare" {
    # The pairing that matters at the repository level: the records and the map
    # are two committed files that can disagree, and this asserts they do not for
    # the harnesses the manifest actually deploys to. #1164 moves this into
    # dotf doctor; until then it lives here, where the real binary already is.
    local rec tier agent
    while IFS= read -r agent; do
        for rec in "$REPO"/harness/agents/*/AGENT.md; do
            [ -f "$rec" ] || continue
            tier="$(awk '/^---[[:space:]]*$/{n++; next} n==1 && /^model:/{sub(/^model:[[:space:]]*/,""); print; exit} n>=2{exit}' "$rec")"
            [ -n "$tier" ] || continue
            run "$DOTF" harness resolve-tier "$tier" --harness "$agent" --repo-root "$REPO"
            [ "$status" -eq 0 ]
            [ -n "$output" ]
        done
    done < <(jq -r '.agents.deploy[].agent' "$REPO/harness/manifest.json")
}

@test "real dotf: a full deploy renders the resolved model id into the agent file" {
    # End to end through the real script and the real binary: the claim the stub
    # suite can only approximate.
    FAKEHOME="${BATS_TEST_TMPDIR:-/tmp}/home_real_$$"
    mkdir -p "$FAKEHOME"
    run env HOME="$FAKEHOME" PATH="$BIN_DIR:$PATH" "$SCRIPT" --deploy
    [ "$status" -eq 0 ]
    F="$FAKEHOME/.claude/agents/curator.md"
    [ -f "$F" ]
    # curator declares `model: top`; claude's top tier is opus
    grep -q '^model: opus' "$F"
    ! grep -q '^model: top' "$F"
    rm -rf "$FAKEHOME"
}
