package doctor

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
)

// orcaTimeoutRe extracts every "timeoutSec": N value declared in orca.json.
var orcaTimeoutRe = regexp.MustCompile(`"timeoutSec"\s*:\s*(\d+)`)

// checkOrcaHook ports healthcheck.ps1 section 13 (DX-006): the Orca-generated
// Copilot hook must not throttle tool calls. orca.json's hook timeoutSec must be
// >= 30, and copilot-hook.ps1 must use the fast HttpWebRequest transport rather
// than Invoke-WebRequest (whose cold init on Windows PowerShell 5.1 blows a short
// timeout, and the CLI then denies the tool call). Both files are regenerated by
// Orca on install, so this is a drift guard — `dotf doctor --fix` or
// scripts/orca-hook-tune.ps1 re-applies the fix. SKIP when Orca is not installed
// (neither file present), the expected state off-Windows and on any box without Orca.
func checkOrcaHook(sys *System, rep *Report, fix bool) {
	rep.Section("Orca Copilot hook (DX-006)")
	home := sys.home()
	orcaJSON := filepath.Join(home, ".copilot", "hooks", "orca.json")
	orcaHook := filepath.Join(home, ".orca", "agent-hooks", "copilot-hook.ps1")

	if !pathExists(orcaJSON) && !pathExists(orcaHook) {
		rep.Skip("Orca Copilot hook — Orca not installed (no ~/.copilot/hooks/orca.json)")
		return
	}

	if pathExists(orcaJSON) {
		switch b, err := os.ReadFile(orcaJSON); {
		case err != nil:
			rep.Fail("orca.json unreadable: " + err.Error())
		case !json.Valid(b):
			// Before any repair: the tuner is a regex, so it happily rewrites a
			// malformed document into a differently malformed one and the write
			// succeeds. Reporting Fix there would claim a repair on a file Orca
			// still cannot load — a success message about an operation whose goal
			// was never checked.
			rep.Fail("orca.json is not valid JSON — fix or remove it; refusing to tune a file Orca cannot load")
		case orcaTimeoutBelow(b, 30):
			if fix {
				tuned := orcaTuneTimeout(b, 30)
				if !json.Valid(tuned) {
					// The input parsed and the output does not: the tuner broke it.
					// Never write that, and never call it a Fix.
					rep.Fail("tuning orca.json would have produced invalid JSON — left untouched")
				} else if err := os.WriteFile(orcaJSON, tuned, 0o644); err != nil {
					rep.Fail("failed to tune orca.json: " + err.Error())
				} else {
					rep.Fix("orca.json: bumped hook timeoutSec to 30 (DX-006)")
				}
			} else {
				if sys.GOOS == "windows" {
					rep.Fail("orca.json hook timeoutSec < 30 — run `dotf doctor --fix` or `orca-hook-tune.ps1` (DX-006)")
				} else {
					rep.Fail("orca.json hook timeoutSec < 30 — run `dotf doctor --fix` (DX-006)")
				}
			}
		default:
			rep.Pass("orca.json hook timeoutSec >= 30 (DX-006)")
		}
	}

	if pathExists(orcaHook) {
		if fileContains(orcaHook, "Invoke-WebRequest") {
			rep.Fail("copilot-hook.ps1 uses slow Invoke-WebRequest — run orca-hook-tune.ps1 (DX-006)")
		} else {
			rep.Pass("copilot-hook.ps1 uses fast HttpWebRequest (DX-006)")
		}
	}
}

// orcaTimeoutBelow reports whether any "timeoutSec" declared in content is below
// min — mirroring the PowerShell check that flags every too-low hook timeout.
func orcaTimeoutBelow(content []byte, min int) bool {
	for _, m := range orcaTimeoutRe.FindAllSubmatch(content, -1) {
		if n, err := strconv.Atoi(string(m[1])); err == nil && n < min {
			return true
		}
	}
	return false
}

// orcaTuneTimeout replaces any "timeoutSec": N where N < min with "timeoutSec": min.
func orcaTuneTimeout(content []byte, min int) []byte {
	return orcaTimeoutRe.ReplaceAllFunc(content, func(match []byte) []byte {
		m := orcaTimeoutRe.FindSubmatch(match)
		if len(m) > 1 {
			if n, err := strconv.Atoi(string(m[1])); err == nil && n < min {
				return []byte(fmt.Sprintf(`"timeoutSec": %d`, min))
			}
		}
		return match
	})
}
