package doctor

import (
	"bytes"
	"errors"
	"path/filepath"
	"strings"
	"testing"
)

// vaultTree builds a temp dir shaped like the knowledge vault: a .git/hooks tree
// and a .pre-commit-config.yaml. Each hookType in installed gets a
// pre-commit-stamped hook file (so vaultHookInstalled recognizes it).
func vaultTree(t *testing.T, installed ...string) string {
	t.Helper()
	vault := t.TempDir()
	mkdirAll(t, filepath.Join(vault, ".git", "hooks"))
	writeFile(t, filepath.Join(vault, ".pre-commit-config.yaml"), "repos: []\n")
	for _, h := range installed {
		writeFile(t, filepath.Join(vault, ".git", "hooks", h),
			"#!/usr/bin/env bash\n# File generated by pre-commit: https://pre-commit.com\n")
	}
	return vault
}

// vaultRecorder is a System that points VAULT_PATH at a temp vault, optionally
// has pre-commit on PATH, and records every CommandOutputDir invocation so the
// --fix path can be asserted on the exact command issued (and its working dir).
type vaultRecorder struct {
	calls   []string
	failCmd bool // true → the recorded `pre-commit install` returns an error
}

func (r *vaultRecorder) system(vault string, hasPreCommit bool) *System {
	return &System{
		Getenv: func(k string) string {
			if k == "VAULT_PATH" {
				return vault
			}
			return ""
		},
		LookPath: func(n string) (string, error) {
			if n == "pre-commit" && !hasPreCommit {
				return "", errors.New("not found: pre-commit")
			}
			return "/usr/bin/" + n, nil
		},
		CommandOutputDir: func(dir, name string, args ...string) (string, error) {
			r.calls = append(r.calls, dir+"$ "+name+" "+strings.Join(args, " "))
			if r.failCmd {
				return "boom", errors.New("exit status 1")
			}
			return "", nil
		},
	}
}

const wantInstallCmd = "pre-commit install --hook-type pre-commit --hook-type pre-push"

func (r *vaultRecorder) installIssued(vault string) bool {
	for _, c := range r.calls {
		if c == vault+"$ "+wantInstallCmd {
			return true
		}
	}
	return false
}

func TestCheckVaultHooks_BothInstalledPasses(t *testing.T) {
	vault := vaultTree(t, "pre-commit", "pre-push")
	r := &vaultRecorder{}
	var buf bytes.Buffer
	rep := capture(&buf)

	checkVaultHooks(r.system(vault, true), rep, true) // fix=true, but already installed

	if rep.Failures() != 0 {
		t.Fatalf("a fully-installed gate must not FAIL, got %d", rep.Failures())
	}
	if len(r.calls) != 0 {
		t.Errorf("idempotent: must not run `pre-commit install` when already installed; calls: %v", r.calls)
	}
	if !strings.Contains(buf.String(), "gitleaks gate active") {
		t.Errorf("want the installed PASS, got: %s", buf.String())
	}
}

func TestCheckVaultHooks_MissingFailsWithoutFix(t *testing.T) {
	vault := vaultTree(t) // no hooks
	r := &vaultRecorder{}
	var buf bytes.Buffer
	rep := capture(&buf)

	checkVaultHooks(r.system(vault, true), rep, false)

	if rep.Failures() != 1 {
		t.Fatalf("a missing gate must FAIL in check mode, got %d", rep.Failures())
	}
	if len(r.calls) != 0 {
		t.Error("check mode must never install; --fix is required")
	}
	if !strings.Contains(buf.String(), "INACTIVE") {
		t.Errorf("want an INACTIVE FAIL, got: %s", buf.String())
	}
}

func TestCheckVaultHooks_InstalledOnFix(t *testing.T) {
	vault := vaultTree(t) // no hooks yet
	r := &vaultRecorder{}
	var buf bytes.Buffer
	rep := capture(&buf)

	checkVaultHooks(r.system(vault, true), rep, true)

	if rep.Failures() != 0 {
		t.Fatalf("--fix with pre-commit available must not FAIL, got %d", rep.Failures())
	}
	if !r.installIssued(vault) {
		t.Errorf("--fix must run `%s` in %s; calls: %v", wantInstallCmd, vault, r.calls)
	}
	if !strings.Contains(buf.String(), "installed vault pre-commit + pre-push hooks") {
		t.Errorf("want a FIX line, got: %s", buf.String())
	}
}

func TestCheckVaultHooks_MissingToolFailsLoudOnFix(t *testing.T) {
	vault := vaultTree(t) // no hooks
	r := &vaultRecorder{}
	var buf bytes.Buffer
	rep := capture(&buf)

	checkVaultHooks(r.system(vault, false), rep, true) // pre-commit NOT on PATH

	if rep.Failures() != 1 {
		t.Fatalf("a present vault with no pre-commit must FAIL loudly under --fix, got %d", rep.Failures())
	}
	if len(r.calls) != 0 {
		t.Error("must not attempt install when pre-commit is absent")
	}
	if !strings.Contains(buf.String(), "pre-commit not on PATH") {
		t.Errorf("want a loud missing-tool FAIL, got: %s", buf.String())
	}
}

func TestCheckVaultHooks_InstallFailureIsReported(t *testing.T) {
	vault := vaultTree(t)
	r := &vaultRecorder{failCmd: true}
	var buf bytes.Buffer
	rep := capture(&buf)

	checkVaultHooks(r.system(vault, true), rep, true)

	if rep.Failures() != 1 {
		t.Fatalf("a failing `pre-commit install` must FAIL, got %d", rep.Failures())
	}
	if !strings.Contains(buf.String(), "`pre-commit install` failed") {
		t.Errorf("want the install-failure FAIL, got: %s", buf.String())
	}
}

func TestCheckVaultHooks_NoVaultSkips(t *testing.T) {
	empty := t.TempDir() // no .git, no config
	r := &vaultRecorder{}
	var buf bytes.Buffer
	rep := capture(&buf)

	checkVaultHooks(r.system(empty, true), rep, true)

	if rep.Failures() != 0 {
		t.Fatalf("an absent vault is a SKIP, not a FAIL, got %d", rep.Failures())
	}
	if len(r.calls) != 0 {
		t.Error("must not install when there is no vault")
	}
	if !strings.Contains(buf.String(), "no secret gate to provision") {
		t.Errorf("want the no-vault SKIP, got: %s", buf.String())
	}
}
