package doctor

import (
	"encoding/json"
	"os"
	"path/filepath"
	"time"

	"github.com/mlorentedev/dotfiles/cli/internal/orca"
)

// checkOrcaHook ports healthcheck.ps1 section 13 (DX-006): the Orca-generated
// Copilot hook must not throttle tool calls. orca.json's hook timeoutSec must be
// >= 30, and copilot-hook.ps1 must use the fast HttpWebRequest transport rather
// than Invoke-WebRequest (whose cold init on Windows PowerShell 5.1 blows a short
// timeout, and the CLI then denies the tool call). Both files are regenerated by
// Orca on install, so this is a drift guard — `dotf doctor --fix` or
// `dotf orca tune-hooks` re-applies the fix, through the same package (CLI-062).
// SKIP when Orca is not installed (neither file present), the expected state
// off-Windows and on any box without Orca.
func checkOrcaHook(sys *System, rep *Report, fix bool) {
	rep.Section("Orca Copilot hook (DX-006)")
	home := sys.home()
	orcaJSON := filepath.Join(home, ".copilot", "hooks", "orca.json")
	orcaHook := filepath.Join(home, ".orca", "agent-hooks", "copilot-hook.ps1")

	if !pathExists(orcaJSON) && !pathExists(orcaHook) {
		rep.Skip("Orca Copilot hook — Orca not installed (no ~/.copilot/hooks/orca.json)")
		return
	}

	if pathExists(orcaJSON) {
		switch b, err := os.ReadFile(orcaJSON); { //nolint:gosec // the user's own hook file
		case err != nil:
			rep.Fail("orca.json unreadable: " + err.Error())
		case !json.Valid(b):
			// Before any repair: the tuner is a regex, so it happily rewrites a
			// malformed document into a differently malformed one and the write
			// succeeds. Reporting Fix there would claim a repair on a file Orca
			// still cannot load — a success message about an operation whose goal
			// was never checked.
			rep.Fail("orca.json is not valid JSON — fix or remove it; refusing to tune a file Orca cannot load")
		case orca.TimeoutBelow(b, orca.DefaultHookTimeout):
			if fix {
				tuned := orca.TuneTimeout(b, orca.DefaultHookTimeout)
				if !json.Valid(tuned) {
					// The input parsed and the output does not: the tuner broke it.
					// Never write that, and never call it a Fix.
					rep.Fail("tuning orca.json would have produced invalid JSON — left untouched")
				} else if err := os.WriteFile(orcaJSON, tuned, 0o644); err != nil { //nolint:gosec // the user's own hook file
					rep.Fail("failed to tune orca.json: " + err.Error())
				} else {
					rep.Fix("orca.json: bumped hook timeoutSec to 30 (DX-006)")
				}
			} else {
				rep.Fail("orca.json hook timeoutSec < 30 — run `dotf doctor --fix` or `dotf orca tune-hooks` (DX-006)")
			}
		default:
			rep.Pass("orca.json hook timeoutSec >= 30 (DX-006)")
		}
	}

	if pathExists(orcaHook) {
		if !fileContains(orcaHook, "Invoke-WebRequest") {
			rep.Pass("copilot-hook.ps1 uses fast HttpWebRequest (DX-006)")
			return
		}
		if !fix {
			rep.Fail("copilot-hook.ps1 uses slow Invoke-WebRequest — run `dotf doctor --fix` or `dotf orca tune-hooks` (DX-006)")
			return
		}
		// CLI-062: the script half of the repair, once PowerShell-only, through
		// the same package `dotf orca tune-hooks` uses — backup beside the file,
		// atomic write, and an unrecognised POST line left alone rather than guessed.
		switch res, err := orca.TuneScriptFile(orcaHook, time.Now); {
		case err != nil:
			rep.Fail("failed to tune copilot-hook.ps1: " + err.Error())
		case res.Unrecognised:
			rep.Fail("copilot-hook.ps1 has Invoke-WebRequest but the POST line is unrecognised — left unchanged; review it by hand (DX-006)")
		default:
			rep.Fix("copilot-hook.ps1: Invoke-WebRequest -> HttpWebRequest (backup " + res.Backup + "; DX-006)")
		}
	}
}
