package doctor

import (
	"path/filepath"
	"strings"
)

// Effectiveness probes for git hooks.
//
// Every hook check in this package has, at some point, answered the wrong
// question — and each time the wrong answer looked like a healthy report:
//
//   - BUG-040: compared core.hooksPath to a literal and called a running
//     dispatcher INACTIVE.
//   - BUG-056: read the GLOBAL core.hooksPath while git resolves the EFFECTIVE
//     one, so a repo-local override disabled the memory-sink guard in the
//     dotfiles repo itself — the repo that ships that guard — and doctor kept
//     reporting "all ok" before and after the guard went from inert to active.
//   - The vault secret gate: tested for .git/hooks/<stage>, a file
//     `pre-commit install` REFUSES to create while core.hooksPath is set. It
//     reported INACTIVE while gitleaks was demonstrably running through the
//     dispatcher's fallback.
//
// Three checks, three different wrong questions, one shape: asking where an
// artifact sits instead of whether the guard fires. These helpers exist so the
// right question is the cheap one to ask. They follow the precedent set by
// System.AgeRoundTrip, which proves a key decrypts rather than that a file
// exists.

// effectiveHooksPath reports the core.hooksPath git will ACTUALLY use inside
// repo. Reading `--global` answers a question about the machine; git resolves
// local-over-global, so only this answers the question about a repo. "" means
// unset, i.e. git falls back to <common-git-dir>/hooks.
func effectiveHooksPath(sys *System, repo string) string {
	// A System assembled without the command seam degrades to "unset", which
	// routes resolution to <common-git-dir>/hooks — the same answer git gives
	// when nothing is configured, and the conservative direction: it can under-
	// report an override, never invent one.
	if sys == nil || sys.CommandOutput == nil {
		return ""
	}
	out, err := sys.CommandOutput("git", "-C", repo, "config", "--get", "core.hooksPath")
	if err != nil {
		return ""
	}
	return strings.TrimSpace(out)
}

// hooksDirFor resolves the directory git reads hooks from for repo, honouring an
// effective hooksPath and otherwise the COMMON git dir — not "$repo/.git/hooks",
// which is a pointer FILE in a linked worktree and under --separate-git-dir
// (BUG-043, the same trap chain-local-hook.sh fell into). A relative hooksPath is
// resolved against the repo, matching git.
func hooksDirFor(sys *System, repo string) string {
	if hp := effectiveHooksPath(sys, repo); hp != "" {
		if filepath.IsAbs(hp) {
			return hp
		}
		return filepath.Join(repo, filepath.FromSlash(hp))
	}
	if sys == nil || sys.CommandOutput == nil {
		return filepath.Join(repo, ".git", "hooks")
	}
	out, err := sys.CommandOutput("git", "-C", repo, "rev-parse", "--git-common-dir")
	common := strings.TrimSpace(out)
	// `git rev-parse` echoes back an option it does not understand and still
	// exits 0, so a git predating --git-common-dir hands back the literal flag.
	// Treat anything that is not a plausible path as "probe failed".
	if err != nil || common == "" || strings.HasPrefix(common, "--") {
		return filepath.Join(repo, ".git", "hooks")
	}
	if !filepath.IsAbs(common) {
		common = filepath.Join(repo, common)
	}
	return filepath.Join(common, "hooks")
}

// hookForStage returns the executable git will run for stage in repo, or "" when
// nothing executable sits there. This is the resolution git performs, not the
// layout we assume it performs.
func hookForStage(sys *System, repo, stage string) string {
	h := filepath.Join(hooksDirFor(sys, repo), stage)
	if !isExecFile(h) {
		return ""
	}
	return h
}

// stageReachesPreCommit reports whether the hook git runs for stage ends up
// invoking pre-commit's gates — the question "is the gate active" actually means.
//
// Two routes count, because both genuinely run the gates:
//
//  1. the hook pre-commit generates (`pre-commit install`), identified by its
//     own marker;
//  2. a GUARD-001 dispatcher, which chains to `pre-commit hook-impl` for any
//     stage the repo has no local hook for. This route is the ONLY one available
//     once core.hooksPath is set machine-wide, because `pre-commit install` then
//     refuses outright ("Cowardly refusing to install hooks with core.hooksPath
//     set"). A check that accepts only route 1 therefore reports every
//     dispatcher-managed repo as unprotected — which is exactly what it did.
//
// The dispatcher route additionally requires a config for it to act on: chaining
// into pre-commit with no .pre-commit-config.yaml is a documented no-op, so it
// would be a gate in name only.
func stageReachesPreCommit(sys *System, repo, stage string) bool {
	hook := hookForStage(sys, repo, stage)
	if hook == "" {
		return false
	}
	if fileContains(hook, "generated by pre-commit") {
		return true
	}
	if isGuardDispatcher(filepath.Dir(hook)) {
		return pathExists(filepath.Join(repo, ".pre-commit-config.yaml"))
	}
	return false
}

// guardRunsIn reports whether the memory-sink guard actually fires for repo.
//
// Cheap enough to answer by resolution rather than execution: the dispatcher's
// pre-commit unconditionally invokes lib/memory-sink-guard.sh before chaining,
// so "the hook git runs for pre-commit lives in a GUARD dispatcher" is
// equivalent to "the guard runs" — and unlike a global-config read, it is false
// exactly when the guard is inert, including under a repo-local override.
func guardRunsIn(sys *System, repo string) bool {
	hook := hookForStage(sys, repo, "pre-commit")
	return hook != "" && isGuardDispatcher(filepath.Dir(hook))
}
