package tools

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// MiseMarker marks the versions.conf pin on the next line as a CLI that
// `dotf tools sync` installs through mise (ADR-044). It sits on its own line,
// not after the value, because every other reader of versions.conf (the
// shell, doctor, setup-windows.ps1) skips comment lines but would read a
// trailing comment as part of the version.
const MiseMarker = "# mise: cli"

// MiseTool is one pinned CLI: the mise tool name and its pin.
type MiseTool struct {
	Name    string
	Version string
}

// ParseMiseTools returns the pins versions.conf marks with MiseMarker, sorted
// by name. The tool name comes from the variable: FOO_BAR_VERSION is mise's
// `foo-bar`, whose short name resolves to the aqua backend. A marker that is
// not directly followed by a non-empty *_VERSION pin is an error, so a marker
// can never silently mark nothing.
func ParseMiseTools(versionsConf []byte) ([]MiseTool, error) {
	lines := strings.Split(strings.ReplaceAll(string(versionsConf), "\r\n", "\n"), "\n")
	var out []MiseTool
	for i, l := range lines {
		if strings.TrimSpace(l) != MiseMarker {
			continue
		}
		if i+1 >= len(lines) {
			return nil, fmt.Errorf("versions.conf line %d: %q marks no pin", i+1, MiseMarker)
		}
		key, value, ok := strings.Cut(strings.TrimSpace(lines[i+1]), "=")
		key, value = strings.TrimSpace(key), strings.TrimSpace(value)
		if !ok || !strings.HasSuffix(key, "_VERSION") || value == "" {
			return nil, fmt.Errorf("versions.conf line %d: %q must be followed by a NAME_VERSION=<pin> line", i+1, MiseMarker)
		}
		name := strings.ToLower(strings.ReplaceAll(strings.TrimSuffix(key, "_VERSION"), "_", "-"))
		out = append(out, MiseTool{Name: name, Version: value})
	}
	sort.Slice(out, func(a, b int) bool { return out[a].Name < out[b].Name })
	return out, nil
}

// RenderMiseConfig is the mise config `dotf tools sync` owns: exact pins,
// sorted, under a header naming the generator.
func RenderMiseConfig(tools []MiseTool) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by `dotf tools sync` from versions.conf (lines marked \"" + MiseMarker + "\").\n")
	b.WriteString("# Do not edit: change the pin in versions.conf and re-run the sync.\n\n[tools]\n")
	for _, t := range tools {
		fmt.Fprintf(&b, "%s = %q\n", t.Name, t.Version)
	}
	return b.Bytes()
}

// MiseConfigDir is the directory mise reads its global config from:
// MISE_CONFIG_DIR, else $XDG_CONFIG_HOME/mise, else ~/.config/mise.
func MiseConfigDir(home string, getenv func(string) string) string {
	if d := getenv("MISE_CONFIG_DIR"); d != "" {
		return d
	}
	if x := getenv("XDG_CONFIG_HOME"); x != "" {
		return filepath.Join(x, "mise")
	}
	return filepath.Join(home, ".config", "mise")
}

// MiseSync converges the pinned CLIs through mise. It owns one file,
// <ConfigDir>/conf.d/dotfiles.toml, and never touches the rest of the mise
// config: a hand-written config.toml keeps working beside it.
type MiseSync struct {
	ConfigDir string
	Run       Runner // `mise ...` and `<tool> --version`; ExecRunner in production
}

// SyncPlan is what a sync would change.
type SyncPlan struct {
	ConfigChanged bool     // the rendered config differs from the file
	Missing       []string // tools that are absent or below their pin
}

// ConfigPath is the file the sync owns.
func (s MiseSync) ConfigPath() string {
	return filepath.Join(s.ConfigDir, "conf.d", "dotfiles.toml")
}

// Plan reports what Apply would do and writes nothing.
func (s MiseSync) Plan(tools []MiseTool) (SyncPlan, error) {
	have, err := os.ReadFile(s.ConfigPath())
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return SyncPlan{}, err
	}
	p := SyncPlan{ConfigChanged: !bytes.Equal(have, RenderMiseConfig(tools))}
	for _, t := range tools {
		if !s.runsAtPin(t) {
			p.Missing = append(p.Missing, t.Name)
		}
	}
	return p, nil
}

// Apply writes the config when it differs, runs `mise install` when anything is
// pending, and then requires every tool to run at or above its pin, through
// `mise which`, not PATH (the shims reach PATH in a later row). It returns the
// plan it acted on; a tool that still does not run is an error naming it.
func (s MiseSync) Apply(tools []MiseTool) (SyncPlan, error) {
	p, err := s.Plan(tools)
	if err != nil {
		return p, err
	}
	if p.ConfigChanged {
		if err := writeFileAtomic(s.ConfigPath(), RenderMiseConfig(tools)); err != nil {
			return p, err
		}
	}
	if !p.ConfigChanged && len(p.Missing) == 0 {
		return p, nil
	}
	if out, err := s.Run("mise", "install"); err != nil {
		return p, fmt.Errorf("mise install: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	after, err := s.Plan(tools)
	if err != nil {
		return p, err
	}
	if len(after.Missing) > 0 {
		return p, fmt.Errorf("after mise install, not running at their pin: %s", strings.Join(after.Missing, ", "))
	}
	return p, nil
}

// runsAtPin resolves the tool through mise and runs it: an install is real
// only when the binary executes and reports at least the pin (lesson 337).
func (s MiseSync) runsAtPin(t MiseTool) bool {
	out, err := s.Run("mise", "which", t.Name)
	path := strings.TrimSpace(string(out))
	if err != nil || path == "" {
		return false
	}
	v := ProbeVersion(path, s.Run)
	return v != "" && atLeast(v, t.Version)
}

// writeFileAtomic writes data to path through a temp file in the same
// directory, so a reader never sees a half-written config.
func writeFileAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".dotfiles-*.toml")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }() // no-op once renamed
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil { //nolint:gosec // a tool list, world-readable by design
		return err
	}
	return os.Rename(tmp.Name(), path)
}
