package tools

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// MiseMarker marks the versions.conf pin on the next line as a CLI that
// `dotf tools sync` installs through mise (ADR-044). It sits on its own line,
// not after the value, because every other reader of versions.conf (the
// shell, doctor, setup-windows.ps1) skips comment lines but would read a
// trailing comment as part of the version.
const MiseMarker = "# mise: cli"

// nearMissRE matches a comment that reads like the marker (`#mise: cli`,
// `# MISE: cli`, `# mise:cli`). Left alone it would be an ordinary comment and
// the pin under it would silently never install.
var nearMissRE = regexp.MustCompile(`(?i)^\s*#\s*mise\s*:`)

// MiseTool is one pinned CLI: the mise tool name and its pin.
type MiseTool struct {
	Name    string
	Version string
}

// ParseMiseTools returns the pins versions.conf marks with MiseMarker, sorted
// by name. The tool name comes from the variable: FOO_BAR_VERSION is mise's
// `foo-bar`, whose short name resolves to the aqua backend. A marker that is
// not directly followed by a non-empty *_VERSION pin is an error, and so is a
// comment that reads like the marker but is not exactly it, so a marker can
// never silently mark nothing.
func ParseMiseTools(versionsConf []byte) ([]MiseTool, error) {
	lines := strings.Split(strings.ReplaceAll(string(versionsConf), "\r\n", "\n"), "\n")
	var out []MiseTool
	for i, l := range lines {
		if strings.TrimSpace(l) != MiseMarker {
			if nearMissRE.MatchString(l) {
				return nil, fmt.Errorf("versions.conf line %d: %q looks like the marker but is not %q; fix it, or the pin under it is never installed", i+1, strings.TrimSpace(l), MiseMarker)
			}
			continue
		}
		if i+1 >= len(lines) {
			return nil, fmt.Errorf("versions.conf line %d: %q marks no pin", i+1, MiseMarker)
		}
		key, value, ok := strings.Cut(strings.TrimSpace(lines[i+1]), "=")
		key, value = strings.TrimSpace(key), strings.TrimSpace(value)
		if !ok || !strings.HasSuffix(key, "_VERSION") || value == "" {
			return nil, fmt.Errorf("versions.conf line %d: %q must be followed by a NAME_VERSION=<pin> line", i+1, MiseMarker)
		}
		name := strings.ToLower(strings.ReplaceAll(strings.TrimSuffix(key, "_VERSION"), "_", "-"))
		out = append(out, MiseTool{Name: name, Version: value})
	}
	if len(out) == 0 {
		// A versions.conf with no marker (one deployed before the markers
		// existed, say) would render an empty config over a converged one and
		// report success.
		return nil, fmt.Errorf("versions.conf has no %q pins: nothing to sync", MiseMarker)
	}
	sort.Slice(out, func(a, b int) bool { return out[a].Name < out[b].Name })
	return out, nil
}

// RenderMiseConfig is the mise config `dotf tools sync` owns: exact pins,
// sorted, under a header naming the generator.
func RenderMiseConfig(tools []MiseTool) []byte {
	var b bytes.Buffer
	b.WriteString("# Generated by `dotf tools sync` from versions.conf (lines marked \"" + MiseMarker + "\").\n")
	b.WriteString("# Do not edit: change the pin in versions.conf and re-run the sync.\n\n[tools]\n")
	for _, t := range tools {
		fmt.Fprintf(&b, "%s = %q\n", t.Name, t.Version)
	}
	// mise is pinned in packages.json; its update notice says `mise self-update`,
	// which would move it past that pin.
	b.WriteString("\n[settings]\ndisable_update_warning = true\n")
	return b.Bytes()
}

// MiseConfigDir is the directory mise reads its global config from:
// MISE_CONFIG_DIR, else $XDG_CONFIG_HOME/mise, else ~/.config/mise.
func MiseConfigDir(home string, getenv func(string) string) string {
	if d := getenv("MISE_CONFIG_DIR"); d != "" {
		return d
	}
	if x := getenv("XDG_CONFIG_HOME"); x != "" {
		return filepath.Join(x, "mise")
	}
	return filepath.Join(home, ".config", "mise")
}

// MiseShimsDir is where mise keeps its shims: MISE_DATA_DIR/shims, else
// $XDG_DATA_HOME/mise/shims, else ~/.local/share/mise/shims. A shim runs the
// tool at the version mise's config selects, with or without `mise activate`.
func MiseShimsDir(home string, getenv func(string) string) string {
	if d := getenv("MISE_DATA_DIR"); d != "" {
		return filepath.Join(d, "shims")
	}
	if x := getenv("XDG_DATA_HOME"); x != "" {
		return filepath.Join(x, "mise", "shims")
	}
	return filepath.Join(home, ".local", "share", "mise", "shims")
}

// MiseSync converges the pinned CLIs through mise. It owns one file,
// <ConfigDir>/conf.d/dotfiles.toml, and never touches the rest of the mise
// config: a hand-written config.toml keeps working beside it.
type MiseSync struct {
	ConfigDir string
	Run       Runner // `mise install` and `<tool> --version`, stdout and stderr merged
	// Stdout runs `mise which`, whose stdout alone is the path: a warning mise
	// prints on stderr must not become part of it. Nil means Run.
	Stdout Runner
}

// SyncPlan is what a sync would change.
type SyncPlan struct {
	ConfigChanged bool     // the rendered config differs from the file
	Missing       []string // tools that are absent or below their pin
}

// ConfigPath is the file the sync owns.
func (s MiseSync) ConfigPath() string {
	return filepath.Join(s.ConfigDir, "conf.d", "dotfiles.toml")
}

// Plan reports what Apply would do and writes nothing.
func (s MiseSync) Plan(tools []MiseTool) (SyncPlan, error) {
	have, err := os.ReadFile(s.ConfigPath())
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return SyncPlan{}, err
	}
	p := SyncPlan{ConfigChanged: !bytes.Equal(have, RenderMiseConfig(tools))}
	for _, t := range tools {
		if !s.runsAtPin(t) {
			p.Missing = append(p.Missing, t.Name)
		}
	}
	return p, nil
}

// Apply writes the config when it differs, runs `mise install` when anything is
// pending, and then requires every tool to run at or above its pin, through
// `mise which`, not PATH (the shims reach PATH in a later row). It returns the
// plan it acted on; a tool that still does not run is an error naming it.
func (s MiseSync) Apply(tools []MiseTool) (SyncPlan, error) {
	p, err := s.Plan(tools)
	if err != nil {
		return p, err
	}
	if p.ConfigChanged {
		if err := writeFileAtomic(s.ConfigPath(), RenderMiseConfig(tools)); err != nil {
			return p, err
		}
	}
	if !p.ConfigChanged && len(p.Missing) == 0 {
		return p, nil
	}
	if out, err := s.Run("mise", "install"); err != nil {
		return p, fmt.Errorf("mise install: %w\n%s", err, strings.TrimSpace(string(out)))
	}
	after, err := s.Plan(tools)
	if err != nil {
		return p, err
	}
	if len(after.Missing) > 0 {
		return p, fmt.Errorf("after mise install, not running at their pin: %s", strings.Join(after.Missing, ", "))
	}
	return p, nil
}

// runsAtPin resolves the tool through mise and runs it: an install is real
// only when the binary executes and reports at least the pin (lesson 337).
func (s MiseSync) runsAtPin(t MiseTool) bool {
	which := s.Stdout
	if which == nil {
		which = s.Run
	}
	out, err := which("mise", "which", t.Name)
	path := strings.TrimSpace(string(out))
	if err != nil || path == "" {
		return false
	}
	v := ProbeVersion(path, s.Run)
	return v != "" && atLeast(v, t.Version)
}

// writeFileAtomic writes data to path through a temp file in the same
// directory, so a reader never sees a half-written config.
func writeFileAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".dotfiles-*.toml")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }() // no-op once renamed
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmp.Name(), 0o644); err != nil { //nolint:gosec // a tool list, world-readable by design
		return err
	}
	return os.Rename(tmp.Name(), path)
}

// HomeRunners returns the runners a machine-level sync uses, both run from
// home so a project mise.toml in the caller's directory is not installed as a
// side effect: run merges stdout and stderr (`mise install`, `<tool>
// --version`), stdout returns stdout alone (`mise which`, whose output is a
// path a stderr warning must not corrupt).
func HomeRunners(home string) (run, stdout Runner) {
	command := func(name string, args ...string) *exec.Cmd {
		c := exec.Command(name, args...) //nolint:gosec // mise, or a tool path mise resolved
		c.Dir = home
		return c
	}
	run = func(name string, args ...string) ([]byte, error) { return command(name, args...).CombinedOutput() }
	stdout = func(name string, args ...string) ([]byte, error) { return command(name, args...).Output() }
	return run, stdout
}
