#!/bin/bash
# init-repo-standards.sh
# Purpose: Mirror the vault pattern index into <target-repo>/docs/standards.md.
#          Pointer-style: SSOT remains the vault. The per-repo file links to
#          canonical pattern definitions, so contributors discover standards
#          without having to know about the vault.
#
# Idempotent: regenerates ONLY between BEGIN/END VAULT STANDARDS markers.
# Custom project standards outside the markers are preserved.
#
# Usage:
#   ./init-repo-standards.sh [--repo <path>] [--vault-url <url>]
#
# Env:
#   VAULT_PATH  vault root (default: $HOME/Projects/knowledge)
#   VAULT_URL   base URL for pattern links (default: GitHub raw URL for vault)
#               Pass empty string to disable links (plain text mode).

set -euo pipefail

usage() {
    cat <<EOF
Usage: init-repo-standards.sh [--repo <path>] [--vault-url <url>]

  --repo <path>       target repo root (default: current git repo)
  --vault-url <url>   override base URL for pattern links
  -h, --help          show this help

VAULT_PATH (env)   vault root (default: \$HOME/Projects/knowledge)
VAULT_URL (env)    default: https://github.com/mlorentedev/knowledge/blob/main/00_meta/patterns
                   empty string disables links (renders plain inline code)
EOF
}

# --- Parse args ---
TARGET_REPO=""
VAULT_URL_OVERRIDE=""
VAULT_URL_OVERRIDE_SET=0

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo) TARGET_REPO="$2"; shift 2 ;;
        --vault-url) VAULT_URL_OVERRIDE="$2"; VAULT_URL_OVERRIDE_SET=1; shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) printf '[ERROR] Unknown option: %s\n' "$1" >&2; usage >&2; exit 1 ;;
    esac
done

# --- Resolve target repo ---
if [[ -z "$TARGET_REPO" ]]; then
    if ! TARGET_REPO="$(git rev-parse --show-toplevel 2>/dev/null)"; then
        printf '[ERROR] Not in a git repo. Use --repo <path> or cd into a repo.\n' >&2
        exit 1
    fi
fi

[[ -d "$TARGET_REPO" ]] || { printf '[ERROR] Repo not found: %s\n' "$TARGET_REPO" >&2; exit 1; }

# --- Resolve vault index ---
VAULT_PATH="${VAULT_PATH:-$HOME/Projects/knowledge}"
INDEX_SRC="$VAULT_PATH/00_meta/patterns/_index.md"

if [[ ! -f "$INDEX_SRC" ]]; then
    printf '[ERROR] Pattern index not found: %s\n' "$INDEX_SRC" >&2
    # shellcheck disable=SC2016
    printf '        Set %s env var to vault root, or clone the vault.\n' '$VAULT_PATH' >&2
    exit 2
fi

# --- Resolve VAULT_URL ---
DEFAULT_VAULT_URL="https://github.com/mlorentedev/knowledge/blob/main/00_meta/patterns"
if [[ "$VAULT_URL_OVERRIDE_SET" -eq 1 ]]; then
    VAULT_URL="$VAULT_URL_OVERRIDE"
else
    VAULT_URL="${VAULT_URL-$DEFAULT_VAULT_URL}"
fi

# --- Strip frontmatter and transform wikilinks ---
# 1. awk: skip first frontmatter block (between first two `---` lines)
# 2. sed: [[name]] → [name](VAULT_URL/name.md), or plain `name` if no URL
INDEX_BODY=$(awk '/^---$/{c++; next} c>=2 {print}' "$INDEX_SRC")

if [[ -n "$VAULT_URL" ]]; then
    # First pass: piped wikilinks [[target|display]] → [display](URL/target.md)
    INDEX_BODY=$(printf '%s\n' "$INDEX_BODY" | sed -E "s#\\[\\[([a-z0-9_-]+)\\|([^]]+)\\]\\]#[\\2]($VAULT_URL/\\1.md)#g")
    # Second pass: simple wikilinks [[target]] → [target](URL/target.md)
    INDEX_BODY=$(printf '%s\n' "$INDEX_BODY" | sed -E "s#\\[\\[([a-z0-9_-]+)\\]\\]#[\\1]($VAULT_URL/\\1.md)#g")
else
    INDEX_BODY=$(printf '%s\n' "$INDEX_BODY" | sed -E "s#\\[\\[([a-z0-9_-]+)\\|([^]]+)\\]\\]#\`\\2\`#g")
    INDEX_BODY=$(printf '%s\n' "$INDEX_BODY" | sed -E "s#\\[\\[([a-z0-9_-]+)\\]\\]#\`\\1\`#g")
fi

# --- Build the generated block ---
TODAY="$(date -u +%Y-%m-%d)"
BEGIN_MARKER="<!-- BEGIN VAULT STANDARDS (auto-generated by init-repo-standards.sh, do not edit between markers) -->"
END_MARKER="<!-- END VAULT STANDARDS -->"
GENERATED_BLOCK=$(cat <<EOF
$BEGIN_MARKER
> Mirror of vault pattern catalog. Canonical source: \`\$VAULT_PATH/00_meta/patterns/_index.md\`. Regenerate with \`init-repo-standards.sh\`.
> Last regenerated: $TODAY.

$INDEX_BODY
$END_MARKER
EOF
)

# --- Write target ---
DOCS_DIR="$TARGET_REPO/docs"
TARGET="$DOCS_DIR/standards.md"
mkdir -p "$DOCS_DIR"

if [[ -f "$TARGET" ]] && grep -qF "$BEGIN_MARKER" "$TARGET"; then
    # Replace existing block between markers (regeneration)
    awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" -v block="$GENERATED_BLOCK" '
        $0 == begin {print block; skip=1; next}
        $0 == end {skip=0; next}
        !skip {print}
    ' "$TARGET" > "${TARGET}.tmp" && mv "${TARGET}.tmp" "$TARGET"
    printf '[OK] Regenerated vault standards block in %s\n' "$TARGET"
elif [[ -f "$TARGET" ]]; then
    # File exists without markers — append (preserve original content above)
    {
        printf '\n'
        printf '%s\n' "$GENERATED_BLOCK"
    } >> "$TARGET"
    printf '[OK] Appended vault standards block to %s\n' "$TARGET"
else
    # New file
    cat > "$TARGET" <<EOF
# Engineering Standards

> Project-specific engineering standards for this repo. The auto-generated block below mirrors the vault pattern catalog; add any project-specific notes above or below it.

$GENERATED_BLOCK
EOF
    printf '[OK] Created %s with vault standards block\n' "$TARGET"
fi
