<#
.SYNOPSIS
    Mirror the vault pattern index into <target-repo>/docs/standards.md.

.DESCRIPTION
    Pointer-style: SSOT remains the vault. The per-repo file links to
    canonical pattern definitions, so contributors discover standards
    without having to know about the vault.

    Idempotent: regenerates ONLY between BEGIN/END VAULT STANDARDS markers.
    Custom project standards outside the markers are preserved.

.PARAMETER Repo
    Target repo root (default: current git repo)

.PARAMETER VaultUrl
    Override base URL for pattern links. Pass empty string to disable links.

.NOTES
    VAULT_PATH (env)  vault root (default: $env:USERPROFILE\Projects\knowledge)
    VAULT_URL (env)   default: https://github.com/mlorentedev/knowledge/blob/main/00_meta/patterns
#>
param(
    [string]$Repo,
    [string]$VaultUrl,
    [switch]$NoLinks
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Track whether VaultUrl was explicitly passed (PowerShell idiom)
$vaultUrlExplicit = $PSBoundParameters.ContainsKey('VaultUrl')

# --- Resolve target repo ---
if (-not $Repo) {
    try {
        $Repo = (& git rev-parse --show-toplevel 2>$null) -replace "`r`n|`r|`n", ''
    } catch {
        $Repo = ''
    }
    if (-not $Repo) {
        Write-Error 'Not in a git repo. Use -Repo <path> or cd into a repo.'
        exit 1
    }
}

if (-not (Test-Path $Repo -PathType Container)) {
    Write-Error "Repo not found: $Repo"
    exit 1
}

# --- Resolve vault index ---
$VaultPath = if ($env:VAULT_PATH) { $env:VAULT_PATH } else { Join-Path $env:USERPROFILE 'Projects\knowledge' }
$IndexSrc = Join-Path $VaultPath '00_meta\patterns\_index.md'

if (-not (Test-Path $IndexSrc -PathType Leaf)) {
    Write-Error "Pattern index not found: $IndexSrc. Set VAULT_PATH env var or clone vault."
    exit 2
}

# --- Resolve VAULT_URL ---
$defaultVaultUrl = 'https://github.com/mlorentedev/knowledge/blob/main/00_meta/patterns'
if ($NoLinks) {
    $resolvedUrl = ''
} elseif ($vaultUrlExplicit) {
    $resolvedUrl = $VaultUrl
} elseif ($env:VAULT_URL) {
    $resolvedUrl = $env:VAULT_URL
} else {
    $resolvedUrl = $defaultVaultUrl
}

# --- Strip frontmatter and transform wikilinks ---
$lines = Get-Content $IndexSrc
$dashCount = 0
$bodyLines = New-Object System.Collections.Generic.List[string]
foreach ($line in $lines) {
    if ($line -eq '---') {
        $dashCount++
        continue
    }
    if ($dashCount -ge 2) {
        $bodyLines.Add($line)
    }
}

# Wikilink transform: handle piped [[target|display]] first, then simple [[target]].
$transformedLines = $bodyLines | ForEach-Object {
    $line = $_
    if ($resolvedUrl) {
        $line = $line -replace '\[\[([a-z0-9_-]+)\|([^\]]+)\]\]', "[`$2]($resolvedUrl/`$1.md)"
        $line = $line -replace '\[\[([a-z0-9_-]+)\]\]', "[`$1]($resolvedUrl/`$1.md)"
    } else {
        $line = $line -replace '\[\[([a-z0-9_-]+)\|([^\]]+)\]\]', '`$2`'
        $line = $line -replace '\[\[([a-z0-9_-]+)\]\]', '`$1`'
    }
    $line
}

$indexBody = $transformedLines -join "`n"

# --- Build the generated block ---
$today = Get-Date -Format 'yyyy-MM-dd'
$beginMarker = '<!-- BEGIN VAULT STANDARDS (auto-generated by init-repo-standards.ps1, do not edit between markers) -->'
$endMarker = '<!-- END VAULT STANDARDS -->'
$generatedBlock = @"
$beginMarker
> Mirror of vault pattern catalog. Canonical source: ``$VaultPath\00_meta\patterns\_index.md``. Regenerate with ``init-repo-standards.ps1``.
> Last regenerated: $today.

$indexBody
$endMarker
"@

# --- Write target ---
$docsDir = Join-Path $Repo 'docs'
$target = Join-Path $docsDir 'standards.md'
if (-not (Test-Path $docsDir)) { New-Item -ItemType Directory -Path $docsDir -Force | Out-Null }

if ((Test-Path $target -PathType Leaf) -and ((Get-Content $target -Raw) -match [regex]::Escape($beginMarker))) {
    # Replace existing block between markers (regeneration)
    $existing = Get-Content $target
    $output = New-Object System.Collections.Generic.List[string]
    $skip = $false
    foreach ($line in $existing) {
        if ($line -eq $beginMarker) {
            $output.Add($generatedBlock)
            $skip = $true
            continue
        }
        if ($line -eq $endMarker) {
            $skip = $false
            continue
        }
        if (-not $skip) { $output.Add($line) }
    }
    Set-Content -Path $target -Value ($output -join "`n") -Encoding UTF8
    Write-Host "[OK] Regenerated vault standards block in $target"
} elseif (Test-Path $target -PathType Leaf) {
    # File exists without markers - append
    Add-Content -Path $target -Value "`n$generatedBlock" -Encoding UTF8
    Write-Host "[OK] Appended vault standards block to $target"
} else {
    # New file
    $content = @"
# Engineering Standards

> Project-specific engineering standards for this repo. The auto-generated block below mirrors the vault pattern catalog; add any project-specific notes above or below it.

$generatedBlock
"@
    Set-Content -Path $target -Value $content -Encoding UTF8
    Write-Host "[OK] Created $target with vault standards block"
}
