<#
.SYNOPSIS
    Re-applies the DX-006 Orca/Copilot PreToolUse hook fix on Windows (idempotent).

.DESCRIPTION
    Orca (Stably AI) regenerates its Copilot agent hooks on every install/upgrade:
      - ~/.copilot/hooks/orca.json           -> registers hooks with "timeoutSec": 5
      - ~/.orca/agent-hooks/copilot-hook.ps1 -> POSTs the event via Invoke-WebRequest

    On Windows PowerShell 5.1 the hook process = a cold powershell.exe spawn (~1.5s)
    PLUS Invoke-WebRequest cold init (~4.5s, the IE/IWR engine). Under load this
    exceeds the 5s timeoutSec, the CLI kills the hook, and EVERY tool call is then
    denied with "hook errored" (DX-006).

    This script removes BOTH root causes, idempotently and reversibly:
      1. orca.json           : bump every hooks.*.timeoutSec below -TimeoutSec up to
                               -TimeoutSec (default 30). Fixes the failures.
      2. copilot-hook.ps1    : swap the Invoke-WebRequest POST for a lightweight
                               System.Net.HttpWebRequest call (~1.5s, no IE init).
                               Fixes the per-tool-call latency.

    Because Orca regenerates these files, this is a RE-APPLY: run it after every Orca
    install/upgrade. setup-windows.ps1 calls it; healthcheck.ps1 / `dotf doctor` flag
    drift back to Orca's defaults.

    Idempotent : a second run with the fix already in place writes nothing.
    Safe       : timestamped .bak before any write, atomic temp+replace, UTF-8 no BOM.
    Reversible : restore the .bak, or just let Orca regenerate the files.

.PARAMETER HookConfig
    Path to Orca's orca.json. Defaults to ~/.copilot/hooks/orca.json.

.PARAMETER HookScript
    Path to Orca's copilot-hook.ps1. Defaults to ~/.orca/agent-hooks/copilot-hook.ps1.

.PARAMETER TimeoutSec
    Minimum hook timeout to enforce in orca.json. Default 30.

.PARAMETER Check
    Report drift only; write nothing. Exit 1 if a fix is missing, 0 if clean or Orca
    is not installed (skip). Used by health checks / CI.

.EXAMPLE
    .\orca-hook-tune.ps1
    Apply the fix to the current user's Orca hooks.

.EXAMPLE
    .\orca-hook-tune.ps1 -Check
    Doctor mode: exit non-zero if the hooks drifted back to Orca's slow defaults.

.NOTES
    DX-006 (#442). Windows-only concern; no-op/skip where the files are absent.
    The two files are GENERATED BY ORCA, not deployed by dotfiles -- that is why the
    fix must be re-applied and why a healthcheck guard makes the drift loud.
#>
[CmdletBinding()]
param(
    [string]$HookConfig = (Join-Path $env:USERPROFILE '.copilot\hooks\orca.json'),
    [string]$HookScript = (Join-Path $env:USERPROFILE '.orca\agent-hooks\copilot-hook.ps1'),
    [int]$TimeoutSec = 30,
    [switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:Utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Plan { param([string]$Message) Write-Host "[orca-hook] $Message" }

function Backup-HookFile {
    param([string]$Path)
    $bak = "$Path.bak.$(Get-Date -Format 'yyyyMMdd-HHmmss')"
    Copy-Item -LiteralPath $Path -Destination $bak -Force
    return $bak
}

function Save-Atomic {
    param([string]$Path, [string]$Content)
    $tmp = "$Path.tmp"
    [System.IO.File]::WriteAllText($tmp, $Content, $script:Utf8NoBom)
    Move-Item -LiteralPath $tmp -Destination $Path -Force
}

# --- Detection ---------------------------------------------------------------
$cfgExists = Test-Path -LiteralPath $HookConfig -PathType Leaf
$scrExists = Test-Path -LiteralPath $HookScript -PathType Leaf

if (-not $cfgExists -and -not $scrExists) {
    Write-Plan 'Orca Copilot hooks not found (Orca not installed for this user) -- nothing to do.'
    exit 0
}

$configContent = if ($cfgExists) { Get-Content -LiteralPath $HookConfig -Raw } else { '' }
$scriptContent = if ($scrExists) { Get-Content -LiteralPath $HookScript -Raw } else { '' }

# orca.json drift: any hook timeoutSec below the floor.
$configDrift = $false
if ($cfgExists) {
    foreach ($m in [regex]::Matches($configContent, '"timeoutSec"\s*:\s*(\d+)')) {
        if ([int]$m.Groups[1].Value -lt $TimeoutSec) { $configDrift = $true; break }
    }
}

# script drift: still uses the slow Invoke-WebRequest for the POST.
$scriptDrift = $false
if ($scrExists) { $scriptDrift = ($scriptContent -match 'Invoke-WebRequest') }

# --- Check mode --------------------------------------------------------------
if ($Check) {
    if ($cfgExists) {
        if ($configDrift) { Write-Plan "DRIFT: $HookConfig has a hook timeoutSec < $TimeoutSec" }
        else { Write-Plan "OK: orca.json hook timeouts >= $TimeoutSec" }
    }
    if ($scrExists) {
        if ($scriptDrift) { Write-Plan 'DRIFT: copilot-hook.ps1 still uses Invoke-WebRequest' }
        else { Write-Plan 'OK: copilot-hook.ps1 uses HttpWebRequest' }
    }
    if ($configDrift -or $scriptDrift) { exit 1 } else { exit 0 }
}

# --- Apply -------------------------------------------------------------------
$changed = 0

if ($cfgExists -and $configDrift) {
    $new = [regex]::Replace($configContent, '"timeoutSec"\s*:\s*(\d+)', {
        param($m)
        if ([int]$m.Groups[1].Value -lt $TimeoutSec) { '"timeoutSec": ' + $TimeoutSec } else { $m.Value }
    })
    $bak = Backup-HookFile $HookConfig
    Save-Atomic $HookConfig $new
    Write-Plan "orca.json: bumped hook timeoutSec -> $TimeoutSec (backup: $bak)"
    $changed++
} elseif ($cfgExists) {
    Write-Plan "orca.json: timeouts already >= $TimeoutSec (no change)"
}

if ($scrExists -and $scriptDrift) {
    # Swap only the single Invoke-WebRequest POST line for an HttpWebRequest block,
    # preserving the rest of Orca's script. If the POST line is not the shape we
    # know, leave it untouched rather than risk breaking a changed Orca script.
    $iwrPattern = '(?m)^([ \t]*)Invoke-WebRequest\b.*$'
    if ($scriptContent -match $iwrPattern) {
        # $1 = captured indentation; the $-prefixed PowerShell vars below are LITERAL
        # output text (single-quoted here-string => no PS expansion; .NET treats $name
        # that is not a group reference as a literal).
        $replacement = @'
$1$uri = 'http://127.0.0.1:' + $env:ORCA_AGENT_HOOK_PORT + '/hook/copilot'
$1$req = [System.Net.HttpWebRequest]::Create($uri)
$1$req.Method = 'POST'
$1$req.ContentType = 'application/json'
$1$req.Headers.Add('X-Orca-Agent-Hook-Token', $env:ORCA_AGENT_HOOK_TOKEN)
$1$req.Timeout = 2000
$1$req.ReadWriteTimeout = 2000
$1$reqBytes = [System.Text.Encoding]::UTF8.GetBytes($body)
$1$req.ContentLength = $reqBytes.Length
$1$reqStream = $req.GetRequestStream()
$1$reqStream.Write($reqBytes, 0, $reqBytes.Length)
$1$reqStream.Close()
$1$resp = $req.GetResponse()
$1$resp.Close()
'@
        $new = [regex]::Replace($scriptContent, $iwrPattern, $replacement)
        $bak = Backup-HookFile $HookScript
        Save-Atomic $HookScript $new
        Write-Plan "copilot-hook.ps1: Invoke-WebRequest -> HttpWebRequest (backup: $bak)"
        $changed++
    } else {
        Write-Plan 'copilot-hook.ps1: has Invoke-WebRequest but the POST line is unrecognized -- left unchanged (review manually, DX-006)'
    }
} elseif ($scrExists) {
    Write-Plan 'copilot-hook.ps1: already HttpWebRequest (no change)'
}

if ($changed -eq 0) {
    Write-Plan 'No changes -- Orca hooks already tuned (DX-006).'
} else {
    Write-Plan "Applied $changed fix(es). Restart the Copilot CLI session to pick up the new orca.json timeout."
}
exit 0
