package env

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Format is the shell dialect of a generated path file.
type Format int

const (
	// FormatSh is POSIX sh (paths.sh), sourced by .bashrc/.zshrc.
	FormatSh Format = iota
	// FormatPs1 is PowerShell (paths.ps1), dot-sourced by profile.ps1.
	FormatPs1
)

const shHeader = "# Generated by `dotf env generate` (ADR-025) — DO NOT EDIT.\n" +
	"# Source of truth: env-contract.json (defaults) + ~/.config/dotfiles/machine.json (overrides).\n" +
	"# Each line keeps an already-set value (cascade rule #1): `${VAR:-default}`.\n"

const ps1Header = "# Generated by `dotf env generate` (ADR-025) — DO NOT EDIT.\n" +
	"# Source of truth: env-contract.json (defaults) + machine.json (overrides).\n" +
	"# Each line keeps an already-set value (cascade rule #1).\n"

// FormatForOS returns the path-file dialect for goos.
func FormatForOS(goos string) Format {
	if goos == "windows" {
		return FormatPs1
	}
	return FormatSh
}

// DefaultOutput is the deployed path-file location for goos under dotfilesDir.
func DefaultOutput(goos, dotfilesDir string) string {
	name := "paths.sh"
	if goos == "windows" {
		name = "paths.ps1"
	}
	return filepath.Join(dotfilesDir, name)
}

// Render produces the path-file content. sh keeps an already-exported value via
// `${VAR:-…}`; ps1 only assigns when the var is unset — both preserve cascade
// rule #1 (an explicit env var wins).
func Render(f Format, vars []ResolvedVar) string {
	var b strings.Builder
	if f == FormatPs1 {
		b.WriteString(ps1Header)
		for _, v := range vars {
			fmt.Fprintf(&b, "if (-not $env:%s) { $env:%s = '%s' }\n", v.Name, v.Name, v.Value)
		}
		return b.String()
	}
	b.WriteString(shHeader)
	for _, v := range vars {
		fmt.Fprintf(&b, "export %s=\"${%s:-%s}\"\n", v.Name, v.Name, v.Value)
	}
	return b.String()
}

// Options configures a Generate run. All inputs are explicit so generation is
// deterministic and unit-testable (no hidden global reads beyond the named
// files).
type Options struct {
	ContractPath string
	MachinePath  string
	GOOS         string
	Home         string
	Output       string
	Check        bool // report drift without writing
	Stdout       bool // return content only, do not touch Output
}

// Result reports what a Generate run produced.
type Result struct {
	Output  string
	Content string
	Drifted bool // Check mode: Output differs from freshly rendered content
	Wrote   bool // write mode: Output was (re)written
}

// Generate renders the path file for the current OS and either writes it
// (idempotent: skips an identical file), checks it for drift, or returns the
// content for stdout.
func Generate(opts Options) (*Result, error) {
	c, err := loadContract(opts.ContractPath)
	if err != nil {
		return nil, err
	}
	m, err := loadMachine(opts.MachinePath)
	if err != nil {
		return nil, err
	}
	vars := Resolve(c, m, opts.GOOS, opts.Home)
	content := Render(FormatForOS(opts.GOOS), vars)
	res := &Result{Output: opts.Output, Content: content}

	if opts.Stdout {
		return res, nil
	}
	if opts.Check {
		existing, _ := os.ReadFile(opts.Output)
		res.Drifted = string(existing) != content
		return res, nil
	}

	if existing, err := os.ReadFile(opts.Output); err == nil && string(existing) == content {
		return res, nil // unchanged — no write, no churn
	}
	if err := os.MkdirAll(filepath.Dir(opts.Output), 0o755); err != nil {
		return nil, fmt.Errorf("create output dir: %w", err)
	}
	if err := os.WriteFile(opts.Output, []byte(content), 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", opts.Output, err)
	}
	res.Wrote = true
	return res, nil
}
